<!DOCTYPE html>
<html>
	<head>


        <?php 
        $today = "monday";
        $spotAvailable = 0;
        $title = "Home";

        include("./includes/connect.inc.php");


        //DEBUG ONLY
        // include('./includes/ChromePhp.php');
        // ChromePhp::log('hello world');

        $query = "SELECT * FROM FACULTY WHERE fac_id=\"testAdmin\"";
        $result = mysqli_query($conn, $query);
        if (!$result){
            die("cannot processed select query");
        }
        $row = mysqli_fetch_assoc($result);



        //
        include_once("./includes/head.php");

        ?>      

       
	
	</head>
	   
   <body id="top" data-spy="scroll" data-target=".header" data-offset="80">
	  

		<!--HEADER-->

<?php include_once("./includes/nav-bar.php") ?>

		<!--/HEADER-->
		

		

				
		<!--HOME-->		
		<section id="sec_1" class="autoheight">
		
		<!--SLIDER-->
		<div id="slides">
			<div class="slides-container">
			  <img src="assets/img/art3.jpg" alt="Cinelli">
			  <img src="assets/img/art5.jpg" alt="Surly">
			  <img src="assets/img/art6.jpg" alt="Cinelli">
			  
			</div>
			<nav class="slides-navigation">
			  <a href="#" class="next  fa fa-2x fa-chevron-right"></a>
			  <a href="#" class="prev  fa fa-2x fa-chevron-left"></a>
			</nav>
		</div>
		<!--/SLIDER-->
		
			<div class="home-bg"></div>
			<div class="col-lg-12 landing-text-pos align-center">
				<h1 class="wow animated fadeInDown" data-wow-duration="1s" data-wow-delay="1s">WELCOME TO MENDOTA UNIVERSITY</h1>
				<hr id="title_hr"/>
				<p class="wow animated fadeInUp" data-wow-duration="1s" data-wow-delay="1s"> Mendota University Center for the Arts</p>
				<a class="learn-more-btn btn-effect wow animated fadeIn" data-wow-duration="0.5s" data-wow-delay="1.5s" data-scroll href="#intro">Learn more</a>
			</div>
		</section>
		<!--/HOME-->
		
        
		<!--ABOUT-->	
        <section class="intro text-center section-padding" id="intro">
			<div class="container wow animated fadeInLeft animated" data-wow-duration="1s" data-wow-delay="0.5s">
				<div class="row">
					<div class="col-lg-8 align-center about">
						<h1 class="arrow">What We're About</h1>
						<hr>
						<p> 
						119-year history as a competitive and innovative undergraduate institution, Mendota University 
						is committed to enriching culture, public life, and democratic discourse by training tomorrow’s
						 thought leaders. Artists and designers of unusual promise and strong motivation are provided an
						  educational context in which they can explore the potential of their own talents in the midst 
						  of an intense critical dialogue. This dialogue is generated by their peers, by distinguished
						   visitors, and by a faculty comprised of professional artists of acknowledged accomplishment.
						 <br></br> <br></br>
						 <h1 class="arrow">Ranked #12 Among Undergraduates Arts Program</h1>
						 <hr>
						 <p>
						The program provides studio spaces workshops, and an environment that encourages experimentation, production, 
						and critical dialogue. Here, students learn from masters in their fields, network with a host of famous alumni, 
						build relationships with working professionals, and benefit from the depth of resources and experiences that 
						only a world-class university in the arts and entertainment capital of the world can offer. With 1,100 undergraduate majors, 
						a vibrant and growing graduate program, a dedicated faculty of internationally recognized artists, designers and a dynamic 
						visiting artist program, Mendota University’s Center For The Arts is a place where students from a variety of backgrounds 
						interact, exchange ideas and cross conventional aesthetic boundaries. </br>
						 </p> <br> </br>
						 <table>
							<tr>
								<td> <img src="assets/img/music.jpg" width="200" height="200" alt="" /> </td>
								<td> <img src="assets/img/camera.jpg" width="300" height="200" alt="" /> </td>
								<td> <img src="assets/img/paint.jpg" width="250" height="200" alt="" /></td>
			</tr>
		</table>
					</div>
				</div>
			</div>
        </section>
		<!--/ABOUT-->	



        
<?php include_once("./includes/footer.php")?>

	<!-- LANDINGPAGE SLIDER  -->
    <script type="text/javascript" src="./assets/js/hammer.min.js"></script>	
		<script type="text/javascript" src="./assets/js/jquery.superslides.js"></script>

        		<!-- INITIALIZATION  -->
		<script type="text/javascript" src="assets/js/init_<?php echo $title?>.js"></script>

	</div>	
		
    </body>
</html>